### PR TITLE
DAO refactoring

### PR DESCRIPTION
**Pull request by w4terbomb**
Made the first part to refactor the code removing the DAO.

There are still some things like DB to refactor. /msyql driver etc.

Note: Check very well before merging, it may contain errors. If you find anything to improve (there are many), let me know, I can correct it and add other things.

### CODE REVIEW

**Comment by Wern-rm** [comment]
Terrible MR - why delete the DAO if it's a programming pattern? You just removed the abstraction level and that's it - without doing anything good...

**Comment by Wern-rm** [comment]
https://www.baeldung.com/java-dao-pattern

**Comment by Wern-rm** [comment]
With this refactoring, you removed the ability to make a Postgres implementation instead of Mysql without breaking MySQL variations.

**Comment by w4terbomb** [comment]
It's not finished yet Wern, I'm just trying to help. This was said to Neon.

**Comment by Wern-rm** [comment]
> It's not finished yet Wern, I'm just trying to help. This was said to Neon.

We need to discuss this change in more detail, as it can both help and harm

**Comment by neon-dev** [comment]
> Terrible MR - why delete the DAO if it's a programming pattern? You just removed the abstraction level and that's it - without doing anything good...

Please keep calm and be respectful.

> We need to discuss this change in more detail

Apparently, yes. I also believe there to be some kind of misunderstanding about this PR, as we all have the same goal in mind.

**Review by neon-dev — APPROVED** [review]

**Comment by neon-dev** [comment]
Thank you for your contribution, highly appreciated!

**Pull request merged**
